<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByIdJoinedToMusee($id)
  {

  	
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT c FROM AppBundle:Commentaire c
              JOIN c.musee m
              WHERE m.id = :id'
          )->setParameter('id', $id);

      try {
          return $query->getArrayResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
          return null;
      }
  }
}
