<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByIdJoinedToMusee($id)
  {

  	
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT p FROM AppBundle:Commentaire p
              JOIN p.musee c
              WHERE p.id = :id'
          )->setParameter('id', $id);

      try {
          return $query->getArrayResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
          return null;
      }
  }
}
