<?php

namespace AppBundle\Repository;

/**
 * MuseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuseeRepository extends \Doctrine\ORM\EntityRepository
{
		public function findArrondissements()
  {

  	
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT DISTINCT m.ville, m.id FROM AppBundle:Musee m'
          );

      try {
          return $query->getArrayResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
          return null;
      }
  }
}
