<?php

namespace AppBundle\Repository\CommentOnMusee;

/**
 * MuseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuseeRepository extends \Doctrine\ORM\EntityRepository
{
}
